# Generated by Django 5.2.1 on 2025-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=30)),
                ('review', models.TextField()),
            ],
        ),
    ]
