# Generated by Django 5.2.1 on 2025-06-18 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0002_view_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
