# Generated by Django 5.2.1 on 2025-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0003_bookings_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, max_length=200, null=True, upload_to='image/')),
            ],
        ),
    ]
