# Generated by Django 5.2.1 on 2025-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0004_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='file',
            field=models.FileField(upload_to='image/'),
        ),
    ]
