# Generated by Django 5.2.1 on 2025-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('about', models.CharField(max_length=60)),
                ('ingredients', models.TextField()),
                ('badge', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
