# Generated by Django 5.2.1 on 2025-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_des',
            name='variant',
            field=models.CharField(choices=[('v', 'Vegetarian Dishes'), ('nv', 'Non-Vegetarian Dishes')], default=None, max_length=25),
            preserve_default=False,
        ),
    ]
